from __future__ import annotations

URGENCY_SURCHARGE_RATE = 0.15
MONTHLY_CONTRACT_DISCOUNT_RATE = 0.10
SEMESTER_CONTRACT_DISCOUNT_RATE = 0.05
INSURANCE_RATE = 0.02
MINIMUM_INSURANCE_PER_TRIP_CLP = 15_000
MONTHLY_CONTRACT_MINIMUM_TRIPS = 4
SEMESTER_CONTRACT_MINIMUM_MONTHS = 6
WEEKLY_TO_MONTHLY_CONTRACT_TRIPS_FACTOR = 4

